[project]
name = "train-times"
version = "0.1.0"
description = "CLI app for quick access to train timetables"
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.128.0",
    "requests>=2.32.5",
]
